version: '3.8'

services:
  splity-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: splity
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: splitydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
